name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build: 
    runs-on: ubuntu-latest 
    strategy:
      matrix:
        node: [12, 14, 16] 
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v2
      with:
        cache: yarn
        node-version: ${{ matrix.node }}
    - run: yarn install
    - run: yarn build
    - run: yarn test --coverage
    - name: Upload Code Coverage
      uses: codecov/codecov-action@v2
      with:
        flags: node-${{ matrix.node }} 
        token: ${{ secrets.CODECOV_TOKEN }}
